cache: bundler
sudo: false
language: ruby
rvm:
  - 2.0
  - 2.2.3
  - jruby-head

gemfile:
  - gemfiles/activerecord_4.1.gemfile
  - gemfiles/activerecord_4.2.gemfile
  - gemfiles/activerecord_5.0.rc1.gemfile
  - gemfiles/activerecord_edge.gemfile

env:
  - DB=sqlite
  - DB=mysql
  - DB=postgresql

#addons:
#  postgresql: "9.3"

script: WITH_ADVISORY_LOCK_PREFIX=$TRAVIS_JOB_ID bundle exec rake --trace spec:all

matrix:
  allow_failures:
    - gemfile: gemfiles/activerecord_edge.gemfile
    - rvm: jruby-head

  exclude:
    - rvm: ruby-head
      gemfile: gemfiles/activerecord_4.1.gemfile
