cache: bundler
language: ruby

rvm:
  - 2.7.1
  - 2.6.3
  - 2.5.5

gemfile:
  - gemfiles/activerecord_6.0.gemfile
  - gemfiles/activerecord_5.2.gemfile
  - gemfiles/activerecord_5.1.gemfile
  - gemfiles/activerecord_5.0.gemfile
  - gemfiles/activerecord_4.2.gemfile
  - gemfiles/activerecord_edge.gemfile

env:
  - DB=sqlite
  - DB=mysql
  - DB=postgresql

services:
  - mysql
  - postgresql

script: WITH_ADVISORY_LOCK_PREFIX=$TRAVIS_JOB_ID bundle exec rake --trace spec:all

matrix:
  allow_failures:
  - gemfile: gemfiles/activerecord_edge.gemfile
  - gemfile: gemfiles/activerecord_6.0.gemfile
  exclude:
  - rvm: 2.5.5
    gemfile: gemfiles/activerecord_edge.gemfile
  - rvm: 2.7.1
    gemfile: gemfiles/activerecord_4.2.gemfile
